Create Buildroot location
edgehog-device-manager/edgehog-buildroot-packages pull request #1
Opened 2022-10-03 16:06 UTC by harlem88

The Buildroot location is outside of the tree. This mechanism allows to keep package recipes, board support and configuration files outside of the Buildroot tree, while still having them nicely integrated in the build logic.

2022-10-05 15:26 UTC, bettio requested changes

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-device-runtime.service
> +WantedBy=multi-user.target
Missing space at the end of file.

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-device-runtime.service
> +Description=Edgehog Device runtime daemon
Let's try to be consistent, e.g. "Edgehog Device Runtime daemon"

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-config.toml
> +download_directory = "/upload/"
download is upload? wat?
Anyway let's stick to LSB filesystem organization. I think the place is `/var/tmp` if we mean updates downloads.

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-config.toml
> +store_directory = "/data/edgehog-device-runtime/"
This sounds like variable data (such as sqlite for inflight messages) that should be placed in `/var/lib/edgehog-device-runtime/`.

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-config.toml
> +interfaces_directory = "/var/lib/edgehog-astarte-interfaces"
This sounds like immutable data, so `/usr/share/edgehog-astarte-interfaces`.

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-device-runtime.mk
> +			$(TARGET_DIR)/var/lib/edgehog-device-runtime/edgehog-config.toml
maybe you should use a variable to avoid repeating each time `$(TARGET_DIR)/var/lib/edgehog-device-runtime/edgehog-config.toml`

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/edgehog-device-runtime.mk
> +$(eval $(cargo-package))
Missing new line at the end of file.

2022-10-05 15:26 UTC, bettio commented on package/edgehog-device-runtime/Config.in
> +            select BR2_PACKAGE_HOST_RUSTC
I think we should also explicitly depend on dbus.

2022-10-05 15:26 UTC, bettio commented on external.mk
> +include $(sort $(wildcard $(BR2_EXTERNAL_EDGEHOG_PATH)/package/*/*.mk))
Missing new line at the end of file.

2022-10-05 15:26 UTC, bettio commented on external.desc
> +desc: Edgehog package recipes
Missing new line at the end of file.

2022-10-05 16:42 UTC, harlem88 commented on package/edgehog-device-runtime/edgehog-config.toml
> +download_directory = "/upload/"
This `upload` label coming from `br2rauc` package recipe, is the Rauc download partition selected by the package... Tomorrow try to understand if it is editable

2022-10-06 09:12 UTC, bettio commented on package/edgehog-device-runtime/edgehog-device-runtime.service
> +Type = simple
simple looks fine, but maybe we should use notify in the future.

2022-10-06 09:54 UTC, harlem88 commented on package/edgehog-device-runtime/edgehog-config.toml
> +store_directory = "/data/edgehog-device-runtime/"
This is referred to `Persistent data partition` in a next release move this to another location, same for `upload`.

2022-10-06 10:15 UTC, bettio approved these changes

2022-10-06 10:16 UTC, merged